-- MySQL Script generated by MySQL Workbench
-- Tue Apr  5 11:12:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema deebeetrain trainingen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deebeetrain trainingen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deebeetrain trainingen` DEFAULT CHARACTER SET latin1 ;
USE `deebeetrain trainingen` ;

-- -----------------------------------------------------
-- Table `deebeetrain trainingen`.`cursus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deebeetrain trainingen`.`cursus` ;

CREATE TABLE IF NOT EXISTS `deebeetrain trainingen`.`cursus` (
  `idcursus` INT NOT NULL,
  `omschrijving` VARCHAR(45) NULL,
  PRIMARY KEY (`idcursus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deebeetrain trainingen`.`medewerker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deebeetrain trainingen`.`medewerker` ;

CREATE TABLE IF NOT EXISTS `deebeetrain trainingen`.`medewerker` (
  `idmedewerker` INT NOT NULL,
  `voornaam` VARCHAR(45) NULL,
  `tussenvoegsel` VARCHAR(45) NULL,
  `achternaam` VARCHAR(45) NULL,
  `idafdeling` INT NULL,
  `chef` INT NOT NULL,
  PRIMARY KEY (`idmedewerker`),
  INDEX `fk_medewerker_afdeling1_idx` (`idafdeling` ASC),
  INDEX `fk_medewerker_medewerker1_idx` (`chef` ASC),
  CONSTRAINT `fk_medewerker_afdeling1`
    FOREIGN KEY (`idafdeling`)
    REFERENCES `deebeetrain trainingen`.`afdeling` (`idafdeling`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medewerker_medewerker1`
    FOREIGN KEY (`chef`)
    REFERENCES `deebeetrain trainingen`.`medewerker` (`idmedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deebeetrain trainingen`.`afdeling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deebeetrain trainingen`.`afdeling` ;

CREATE TABLE IF NOT EXISTS `deebeetrain trainingen`.`afdeling` (
  `idafdeling` INT NOT NULL,
  `omschrijving` VARCHAR(45) NULL,
  `hoofd` INT NULL,
  PRIMARY KEY (`idafdeling`),
  INDEX `fk_afdeling_medewerker1_idx` (`hoofd` ASC),
  CONSTRAINT `fk_afdeling_medewerker1`
    FOREIGN KEY (`hoofd`)
    REFERENCES `deebeetrain trainingen`.`medewerker` (`idmedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deebeetrain trainingen`.`uitvoering`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deebeetrain trainingen`.`uitvoering` ;

CREATE TABLE IF NOT EXISTS `deebeetrain trainingen`.`uitvoering` (
  `iduitvoering` INT NOT NULL,
  `datum` DATE NULL,
  `idmedewerker` INT NULL,
  `evaluatie` INT NULL,
  `idcursus` INT NULL,
  PRIMARY KEY (`iduitvoering`),
  INDEX `fk_uitvoering_cursus1_idx` (`idcursus` ASC),
  CONSTRAINT `fk_uitvoering_cursus1`
    FOREIGN KEY (`idcursus`)
    REFERENCES `deebeetrain trainingen`.`cursus` (`idcursus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deebeetrain trainingen`.`medewerker_has_uitvoering`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `deebeetrain trainingen`.`medewerker_has_uitvoering` ;

CREATE TABLE IF NOT EXISTS `deebeetrain trainingen`.`medewerker_has_uitvoering` (
  `medewerker_idmedewerker` INT NOT NULL,
  `uitvoering_iduitvoering` INT NOT NULL,
  PRIMARY KEY (`medewerker_idmedewerker`, `uitvoering_iduitvoering`),
  INDEX `fk_medewerker_has_uitvoering_uitvoering1_idx` (`uitvoering_iduitvoering` ASC),
  INDEX `fk_medewerker_has_uitvoering_medewerker_idx` (`medewerker_idmedewerker` ASC),
  CONSTRAINT `fk_medewerker_has_uitvoering_medewerker`
    FOREIGN KEY (`medewerker_idmedewerker`)
    REFERENCES `deebeetrain trainingen`.`medewerker` (`idmedewerker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medewerker_has_uitvoering_uitvoering1`
    FOREIGN KEY (`uitvoering_iduitvoering`)
    REFERENCES `deebeetrain trainingen`.`uitvoering` (`iduitvoering`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
