-- MySQL Script generated by MySQL Workbench
-- Wed Apr  6 11:09:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Apotheek
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Apotheek
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Apotheek` DEFAULT CHARACTER SET utf8 ;
USE `Apotheek` ;

-- -----------------------------------------------------
-- Table `Apotheek`.`Apotheek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Apotheek`.`Apotheek` (
  `idApotheek` INT NOT NULL,
  `patientnr` INT NULL,
  `patientnaam` VARCHAR(45) NULL,
  `geboorte-datum` INT NULL,
  `huisarts-code` VARCHAR(45) NULL,
  `huisarts-naam` VARCHAR(45) NULL,
  `datum-aankoop` DATE NOT NULL,
  PRIMARY KEY (`idApotheek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Apotheek`.`medicijnen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Apotheek`.`medicijnen` (
  `idmedicijnen` INT NOT NULL,
  `medicijnen-code` INT NULL,
  `omschrijving` VARCHAR(45) NULL,
  `hoeveelheid` INT NULL,
  PRIMARY KEY (`idmedicijnen`),
  CONSTRAINT `fk_medicijnen_Apotheek`
    FOREIGN KEY (`idmedicijnen`)
    REFERENCES `Apotheek`.`Apotheek` (`idApotheek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
