-- MySQL Script generated by MySQL Workbench
-- Wed Apr  6 10:26:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hondenuitlaatservice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hondenuitlaatservice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hondenuitlaatservice` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `Hondenuitlaatservice` ;

-- -----------------------------------------------------
-- Table `Hondenuitlaatservice`.`honden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hondenuitlaatservice`.`honden` ;

CREATE TABLE IF NOT EXISTS `Hondenuitlaatservice`.`honden` (
  `idhonden` INT NOT NULL,
  `hondnaam` VARCHAR(45) NULL,
  `chipnr` INT NULL,
  `ras` VARCHAR(45) NULL,
  `telefoon` INT NULL,
  PRIMARY KEY (`idhonden`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hondenuitlaatservice`.`uitlaatrooster`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hondenuitlaatservice`.`uitlaatrooster` ;

CREATE TABLE IF NOT EXISTS `Hondenuitlaatservice`.`uitlaatrooster` (
  `iduitlaatrooster` INT NOT NULL,
  `chipnr` INT NULL,
  `datum` DATE NULL,
  `duur` INT NULL,
  `code_medewerker` VARCHAR(45) NULL,
  `naam_medewerker` VARCHAR(45) NULL,
  PRIMARY KEY (`iduitlaatrooster`),
  CONSTRAINT `fk_uitlaatrooster_honden1`
    FOREIGN KEY (`iduitlaatrooster`)
    REFERENCES `Hondenuitlaatservice`.`honden` (`idhonden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
